// Public API surface for `@loki/core`.
//
// M1 ships the schema DSL: tenant / actor / account / transaction
// builders, runtime validation, primitive types (postings, currency,
// ULID). The engine, runtime client, reconciler, hooks, and adapter
// SDK are layered on top in subsequent batches per `project.md` §18.

// --- schema DSL builders ---
export { defineTenant } from './schema/tenant.js'
export type { TenantInput } from './schema/tenant.js'

export { defineActor } from './schema/actor.js'
export type { ActorInput } from './schema/actor.js'

export { defineTransaction, NONE_STATE } from './schema/transaction.js'
export type {
  TransactionInputArgs,
  TransitionFactory,
} from './schema/transaction.js'

export { defineProjection, defineSchema, diffSchemas } from './schema/schema.js'
export type {
  ChangeKind,
  ProjectionInput,
  SchemaChange,
  SchemaDiff,
  SchemaInputArgs,
} from './schema/schema.js'
export type { AliasMap, ProjectionColumn, ProjectionDef } from './schema/types.js'

// --- schema types (runtime + type-only) ---
export type {
  AccountDef,
  AccountInstanceRef,
  AccountOptions,
  AccountSpecMap,
  ActorDef,
  Direction,
  InferPayload,
  InvariantFn,
  NoneState,
  ParticipantHandle,
  Posting,
  PostingDraft,
  PostingsFn,
  PostingsInvertRef,
  PostingsSpec,
  ResolvedParticipants,
  SchemaDef,
  SchemaInput,
  SchemaKind,
  TenantDef,
  TransactionDef,
  TransactionInput,
  TransitionContext,
  TransitionDef,
  TransitionInput,
} from './schema/types.js'

// --- validation ---
export { validateSchema } from './schema/validate.js'
export type { ValidateOptions, ValidateResult } from './schema/validate.js'
export { SchemaError } from './schema/errors.js'
export type { SchemaIssue, SchemaIssueCode } from './schema/errors.js'

// --- primitives ---
export { isBalanced, sumByDirection, sumByDirectionPerCurrency } from './primitives/posting.js'
export {
  ZERO,
  defineCurrency,
  defineCurrencyMap,
  formatMinor,
  isNonNegative,
  isPositive,
  splitAmount,
} from './primitives/currency.js'
export type {
  CurrencyCode,
  CurrencyDefInput,
  CurrencyMap,
  CurrencyMeta,
  RoundingMode,
} from './primitives/currency.js'
export { ULID_REGEX, ulid } from './primitives/ulid.js'
export {
  SIGNATURE_HEADER,
  TIMESTAMP_HEADER,
  signOutboxPayload,
  verifyInboundSignature,
} from './primitives/hmac.js'
export type { SignedHeaders, VerifyOptions } from './primitives/hmac.js'
export {
  DEFAULT_ALGORITHM as PAYLOAD_CRYPTO_DEFAULT_ALGORITHM,
  ENCRYPTED_KEY,
  ENVELOPE_VERSION,
  decryptPayload,
  encryptPayload,
  isEncryptedEnvelope,
} from './primitives/payload-crypto.js'
export type { PayloadCrypto } from './primitives/payload-crypto.js'

// --- DDL / migrations ---
export {
  buildDropIndexesSql,
  buildDropRlsSql,
  buildDropRolesSql,
  buildDropTablesSql,
  buildGrantsSql,
  buildIndexesSql,
  buildRlsSql,
  buildRolesSql,
  buildTablesSql,
  DEFAULT_OPTIONS as DEFAULT_MIGRATION_OPTIONS,
  ENGINE_TABLES,
  ident,
  inList,
  literal,
  literalString,
  planInitialMigration,
  resolveOptions,
  SqlError,
  TENANT_GUC,
  trimSql,
} from './db/index.js'
export type {
  EngineTable,
  MigrationOptions,
  MigrationPlan,
  PartitioningStrategy,
  ResolvedMigrationOptions,
  TenancyMode,
} from './db/index.js'

// --- engine ---
export {
  ActorNotPermittedError,
  buildAccountOps,
  buildAdminOps,
  buildOutboxOps,
  buildRecordOps,
  buildTenantClient,
  canonicalize,
  CanonicalizationError,
  canonicalizeToString,
  CompromisedRecordError,
  ConcurrencyConflictError,
  computePostingsChecksum,
  computeRowHash,
  createEngine,
  BeforeTransitionTimeoutError,
  createHookRegistry,
  createMigrator,
  createReconciler,
  DatabaseError,
  DEFAULT_SEVERITY,
  ENGINE_TENANT_GUC,
  IllegalStateTransitionError,
  InvalidPostingError,
  OverdraftError,
  isSagaSuccess,
  KeyAlreadyConsumedError,
  LokiError,
  markResolved,
  runSaga,
  matchesHookFilter,
  MIGRATIONS_TABLE,
  MigrationMismatchError,
  RECONCILER_STATE_TABLE,
  buildPartitionsOps,
  buildFxOps,
  buildHoldsOps,
  buildDisputesOps,
  buildScheduler,
  buildInstruments,
  consoleLogger,
  NOOP_LOGGER,
  NOOP_METRICS,
  NOOP_TRACER,
  DEFAULT_POOL_OPTIONS,
  gracefulShutdown,
  installShutdownHandlers,
  compareLsn,
  nextFireMs,
  openConnection,
  withSearchPath,
  recordAnomaly,
  RejectTransition,
  sha256Hasher,
  UnbalancedPostingsError,
  UnknownTransitionError,
  buildQueryOps,
  decodeCursor,
  encodeCursor,
} from './engine/index.js'
export type {
  AccountAggregate,
  AccountAggregateArgs,
  AccountAggregateMetric,
  AccountHistoryArgs,
  AccountIdentity,
  AccountOps,
  AccountQueryOps,
  AccountRow,
  AdapterContract,
  AdapterInboundContext,
  AdapterInboundResult,
  AdapterOutboundContext,
  AdaptersOps,
  AdapterTransitionAction,
  ActorRef,
  ActorScopedOps,
  ActorSummary,
  ActorSummaryArgs,
  ActorTransactionsArgs,
  AdminOps,
  AfterTransitionEvent,
  AmountFilter,
  AnomalyCheckName,
  AnomalyDraft,
  AnomalyEvent,
  AnomalyRow,
  AnomalySeverity,
  AppliedMigration,
  BeforeTransitionEvent,
  BulkTransitionItem,
  CanonicalValue,
  Connection,
  ConnectionInput,
  Counter,
  EngineInstruments,
  EngineLike,
  GracefulShutdownOptions,
  ShutdownTarget,
  Gauge,
  Histogram,
  LogFields,
  LogLevel,
  Logger,
  MetricLabels,
  MetricsAdapter,
  Span,
  SpanStatus,
  Tracer,
  ReadYourWritesMode,
  RuntimeRoles,
  CreateAccountInput,
  CreateRecordInput,
  CreateRecordResult,
  CreateTenantInput,
  Cursor,
  DateLike,
  DatabaseHealth,
  Engine,
  EngineOptions,
  EnginePosting,
  HealthCheckOptions,
  HealthReport,
  ReplicaHealth,
  FindManyAnomaliesArgs,
  FindManyPostingsArgs,
  FindManyTransactionsArgs,
  FindManyTransitionsArgs,
  Hasher,
  HookFailureEvent,
  HookFilter,
  HookHandler,
  HookRegistry,
  HookRegistryOptions,
  HookUnsubscribe,
  IntegrityViolationEvent,
  Migrator,
  MigratorStatus,
  Order,
  OutboxDispatch,
  OutboxEvent,
  OutboxFailureTerminalEvent,
  OutboxHandler,
  OutboxOps,
  OutboxWorkerHandle,
  OutboxWorkerOptions,
  Page,
  QuarantineEvent,
  QueryOps,
  Reconciler,
  ReconcilerContext,
  ReconcilerHandle,
  ReconcilerSchedule,
  ReconcilerStartOptions,
  ReconciliationCompleteEvent,
  RecordOps,
  ReversalEvent,
  RunOnceOptions,
  RunOnceResult,
  RunDueOptions,
  RunDueResult,
  EnsureForOptions,
  EnsuredPartition,
  PartitionTable,
  PartitionsOps,
  FxOps,
  FxRate,
  FxRateHistoryInput,
  LookupFxRateInput,
  PublishFxRateInput,
  Hold,
  HoldStatus,
  HoldsOps,
  PlaceHoldInput,
  ReleaseHoldInput,
  ExpireHoldsResult,
  Dispute,
  DisputeStatus,
  DisputesOps,
  OpenDisputeInput,
  ResolveDisputeInput,
  ExpireDisputesResult,
  ScheduledTransition,
  ScheduledTransitionStatus,
  Scheduler,
  SchedulerWorkerHandle,
  SchedulerWorkerOptions,
  ListScheduledFilter,
  CreateScheduledTransitionInput,
  SagaContext,
  SagaOptions,
  SagaResult,
  SagaStep,
  SchemaMigrationEvent,
  TenantLifecycleEvent,
  TenantSnapshot,
  VerifyResult,
  SqlClient,
  SqlTransaction,
  TenantClient,
  TenantOps,
  TenantRow,
  TransitionInputArgs,
  TransitionResult,
  TxnRecord,
  TxnTransition,
} from './engine/index.js'

// --- meta ---
export { LOKI_CORE_VERSION, LOKI_COMPAT_MAJOR, assertMinCompat } from './version.js'
